// ===================================
// Application Configuration
// ===================================

const CONFIG = {
    // API Configuration
    API_BASE_URL: 'https://api.openstreetmap.org/api/0.6',
    API_TIMEOUT: 30000, // 30 seconds
    
    // Search Defaults
    DEFAULT_LIMIT: 9999,
    MAX_LIMIT: 10000,
    CLOSED_DAYS: 3650, // 10 years
    
    // Map Configuration
    MAP: {
        CENTER: [50.8371, 4.3676], // Brussels coordinates
        ZOOM: 11,
        MIN_ZOOM: 7,
        MAX_ZOOM: 18,
        BELGIUM_BOUNDS: [
            [49.490919, 2.542619], // Southwest
            [51.508742, 7.232075]  // Northeast
        ],
        DEFAULT_BBOX: '4.218750,50.757310,4.571342,50.930089'
    },
    
    // Tile Layer
    TILES: {
        URL: 'https://tile.openstreetmap.be/osmbe/{z}/{x}/{y}.png',
        ATTRIBUTION: '&copy; <a href="https://www.openstreetmap.org/copyright/en">OpenStreetMap</a> contributors, Tiles generated by <a href="https://www.champs-libres.coop/">Champs-Libres</a>',
        MAX_ZOOM: 18
    },
    
    // Marker Clustering
    CLUSTER: {
        ENABLED: true,
        MAX_RADIUS: 50,
        SPIDERFY_ON_MAX_ZOOM: true,
        SHOW_COVERAGE_ON_HOVER: true,
        ZOOM_TO_BOUNDS_ON_CLICK: true,
        DISABLE_AT_ZOOM: 16,
        ANIMATE: true
    },
    
    // Custom Marker Icons
    ICONS: {
        OPEN: {
            iconUrl: 'data:image/svg+xml;base64,' + btoa(`
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="41" viewBox="0 0 25 41">
                    <path fill="#28a745" stroke="#fff" stroke-width="2" d="M12.5 0C5.6 0 0 5.6 0 12.5c0 9.4 12.5 28.5 12.5 28.5S25 21.9 25 12.5C25 5.6 19.4 0 12.5 0z"/>
                    <circle cx="12.5" cy="12.5" r="6" fill="#fff"/>
                </svg>
            `),
            iconSize: [25, 41],
            iconAnchor: [12, 41],
            popupAnchor: [1, -34],
            shadowUrl: 'https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png',
            shadowSize: [41, 41]
        },
        CLOSED: {
            iconUrl: 'data:image/svg+xml;base64,' + btoa(`
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="41" viewBox="0 0 25 41">
                    <path fill="#dc3545" stroke="#fff" stroke-width="2" d="M12.5 0C5.6 0 0 5.6 0 12.5c0 9.4 12.5 28.5 12.5 28.5S25 21.9 25 12.5C25 5.6 19.4 0 12.5 0z"/>
                    <path fill="#fff" d="M8 8l9 9M17 8l-9 9" stroke="#fff" stroke-width="2"/>
                </svg>
            `),
            iconSize: [25, 41],
            iconAnchor: [12, 41],
            popupAnchor: [1, -34],
            shadowUrl: 'https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png',
            shadowSize: [41, 41]
        }
    },
    
    // Storage Keys
    STORAGE: {
        RECENT_SEARCHES: 'osm_notes_recent_searches',
        THEME: 'osm_notes_theme',
        MAX_RECENT: 5
    },
    
    // UI Configuration
    UI: {
        STATUS_DISPLAY_TIME: 3000, // 3 seconds
        ANIMATION_DURATION: 300, // 300ms
        DEBOUNCE_DELAY: 500 // 500ms
    },
    
    // Export Configuration
    EXPORT: {
        JSON_INDENT: 2,
        CSV_DELIMITER: ',',
        DATE_FORMAT: 'YYYY-MM-DD HH:mm:ss'
    },
    
    // Messages
    MESSAGES: {
        LOADING: 'Searching...',
        SUCCESS: 'Search completed successfully',
        ERROR: 'An error occurred',
        NO_RESULTS: 'No results found',
        EMPTY_QUERY: 'Please provide at least one search criterion'
    }
};

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = CONFIG;
}
